.TH ST 1 st-VERSION
.SH NAME
st \- simple terminal
.SH SYNOPSIS
.B st
.RB [ \-c
.IR class ]
.RB [ \-t 
.IR title ]
.RB [ \-v ]
.RB [ \-e
.IR cmd ]
.SH BESCHREIBUNG
.B st
ist ein einfacher Terminal-Emulator.
.SH OPTIONEN
.TP
.B \-t Titel
Überschreibt den vorausgewählten Titel (st)
.TP
.B \-c class
Überschreibt die vorausgewählte Klasse ($TERM)
.TP
.B \-v
Gibt Versionsinformationen über die Standardausgabe aus und beendet st dann.
.TP
.B \-e cmd [argumente]
Führt den Befehl cmd anstelle der Shell aus. Gib deinen Befehl so an, wie du ihn sonst in der Shell eingeben würdest. Wird diese Option genutzt, so
.BI "muß sie in der Reihenfolge die letzte sein"
! Dies ist dasselbe Verhalten wie bei xterm/rxvt.

